# -*- coding: utf-8 -*-
"""Homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SH0jh8LWd1U-4F1LhOZhGQlTnvtjdr0
"""

UID = 119186367
Last_Name = "Patel"
First_Name = "Dadhija"


def caesar_str_enc(text, shift):
  x = text.upper()
  cipher=""
  count=0
  while count<len(x):
    ascii = ord(x[count])
    if ascii>=65 and ascii<=90:
      temp = (ascii-65+shift)%26
      temp+=65
      cipher = cipher + chr(temp)
    count+=1
  return cipher

def caesar_str_dec(text, shift):
  x = text.upper()
  plain=""
  count=0 
  while count<len(x):
    ascii = ord(x[count])
    if ascii>=65 and ascii<=90:
      temp = (ascii-65-shift)%26
      temp+=65
      plain = plain + chr(temp) 
    count+=1
  return plain


if __name__ == "__main__":
  text = "A Test Sentence"
  cipher_text = caesar_str_enc(text, 2)
  print(cipher_text)

  plain_text = caesar_str_dec(cipher_text, 2)
  print(plain_text)